/**
 * index.ts — Worker entry point
 *
 * Polls pgmq(trade_signals) for signals from TradingView via Edge Function.
 * Executes market orders via BinanceAdapter.
 *
 * ── Queue message contract (WB1 v1.0 — frozen 2026-06-04) ────────────────────
 *   { schema_version: '1.0', bot_id: string, signal_id: string, side: 'buy'|'sell' }
 *   - schema_version : REQUIRED, must equal '1.0' — reject otherwise (F-02).
 *                      The field exists so a future format can never be
 *                      misread as v1.0; enforcing it is what makes it real.
 *   - symbol         : loaded from bots.trading_pair — never from message
 *   - client_order_id: generated by Worker (PRX_<nanoid(10)>) — never from message
 *   See Decision Log: "Queue Message Format v1.0" (supersedes Option A 2026-06-01)
 *
 * ── pgmq RPC wrappers (migration 007 — applied 2026-06-04) ────────────────────
 *   pgmq_read(queue_name, vt, qty)  → message rows
 *   pgmq_delete(queue_name, msg_id) → boolean
 *   The poll loop stays gated behind QUEUE_ENABLED until WB6 E1 validation.
 *
 * ── QUEUE_ENABLED (Decision 2026-06-03) ───────────────────────────────────────
 *   Optional env flag, default false. Controls whether the poll loop runs.
 *   false (Sprint 2): reconcile, log worker_queue_disabled once, stay alive idle.
 *   true  (Sprint 3): preflight pgmq_read (fail fast if missing), then poll.
 *
 * ── Boot sequence ─────────────────────────────────────────────────────────────
 *   1. Validate env (SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, PRAXIS_IS_PRODUCTION,
 *      QUEUE_ENABLED; DOPPLER_ENVIRONMENT warn-only)
 *   2. Create Supabase client (service_role, no session persistence)
 *   3. Boot reconciliation — find stuck pending/unknown trades → reconciliation_jobs
 *   4. QUEUE_ENABLED=false → idle keep-alive; true → preflight + poll loop
 *      until SIGTERM / SIGINT
 *
 * ── processMessage steps ──────────────────────────────────────────────────────
 *   0.  Validate message shape
 *   1.  Fetch bot
 *   2.  Check bot.status === 'active'
 *   2.5 Guard: credential_id null → disable bot, ack (ENG-007)
 *   3.  Idempotency — UNIQUE(bot_id, signal_id); unknown → upsert recon_job
 *   3.5 Guard: unresolved unknown trades → ack=false, block bot (ENG-004)
 *   4a. Resolve user_exchange_credentials by bot.credential_id → vault_secret_id;
 *       gates: status='valid', not deleted, UUID-shaped pointer (F-01, 2026-06-11).
 *       Vault receives vault_secret_id — NEVER the credentials row id.
 *   4.  Build BinanceAdapter
 *   5.  Get market rules (symbol from bots.trading_pair)
 *   6.  Calculate quantity (BUY: minimum safe / SELL: 95% of free balance)
 *   7.  INSERT trades(pending) — BEFORE any exchange call
 *   8.  createOrder()
 *   9.  UPDATE trades(submitted|filled)
 *  10.  Error handling: three-way split (see below)
 *
 * ── Error classification ──────────────────────────────────────────────────────
 *   Immediate disable — ack, no threshold, credential → 'invalid', bot → 'error':
 *     VaultSecretNotFoundError → trade: failed, DLQ, disableCredentialAndBot
 *     ExchangeAuthError        → trade: failed, DLQ, disableCredentialAndBot
 *
 *   Threshold-based permanent — ack, failures++, circuit breaker at 5:
 *     ExchangeRejectedError    → trade: failed, DLQ, consecutive_failures++
 *
 *   Transient — inline fetchOrder attempted once (ENG-004, Option B):
 *     fetchOrder → filled|submitted|cancelled|failed  → update trade, ack=true
 *     fetchOrder → null (OrderNotFound)               → trade: failed, ack=true (no DLQ, no failures++)
 *     fetchOrder → throws transient                   → trade: unknown, reconciliation_job, ack=true
 *     DB errors (pre-INSERT)                          → no trade written, ack=false (retry)
 *
 *   UPDATE failure after createOrder success:
 *     → trade: unknown, reconciliation_job immediately, ack=true (don't risk duplicate order)
 *
 *   Skip — ack, no trade written:
 *     Malformed message shape
 *     Bot not found / not active / null credential
 *     Credential row missing / deleted / not-valid / malformed vault pointer
 *       → bot disabled, credential row UNTOUCHED (F-01)
 *     Duplicate signal (idempotency — terminal status)
 *     Unknown trade re-queued → upsert reconciliation_job, ack=true
 *     SELL with no sellable position
 *     Race-condition duplicate INSERT (23505 on bot_id+signal_id)
 *
 * ── Circuit breaker ───────────────────────────────────────────────────────────
 *   bots.consecutive_failures increments on ExchangeRejectedError only.
 *   >= MAX_CONSECUTIVE_FAILURES (5) → bot.status = 'error'. Manual reset required.
 *   Reset to 0 only on filled or submitted (NOT cancelled — ENG-008).
 *
 * ── ⚠️  POSITION AMBIGUITY RISK (ENG-004 — Decision Log 2026-06-02) ───────────
 *   WINDOW: createOrder() dispatched → fetchOrder() resolves (Step 8b)
 *
 *   During this window the exchange position state is unknown:
 *   the order may or may not have been submitted. If a second signal arrives
 *   during this window it is blocked by Step 3.5 (unknown trade guard),
 *   preventing double-exposure.
 *
 *   RESOLUTION — Option B (inline fetchOrder, decided 2026-06-02):
 *     createOrder() timeout → immediate fetchOrder(clientOrderId) once:
 *       filled|submitted|cancelled → resolve trade inline, ack, no recon job
 *       OrderNotFound (null)       → order never reached exchange, trade=failed, ack
 *       fetchOrder also times out  → trade=unknown, recon_job, bot blocked via 3.5
 *
 *   Only genuinely unresolvable trades (network outage across BOTH calls) enter
 *   reconciliation. Never ack a transient failure without either a resolved trade
 *   or a reconciliation_job — no silent unresolved position state allowed.
 *
 *   VISIBILITY TIMEOUT IMPACT:
 *   Inline fetchOrder adds a second exchange round-trip to worst-case duration.
 *   Formula revised: worst_case = T_vault + 2 × T_timeout + T_db + overhead
 *   Required: T_timeout ≤ 5000ms (set in BinanceAdapter) to stay within 30s VT.
 *   See Decision Log: "pgmq visibility_timeout — PENDING MEASUREMENT"
 *
 * ── Deferred to Sprint 3 (see Decision Log) ──────────────────────────────────
 *   Reconciliation setInterval(60s)
 *   Trade quantity: configurable position_size_pct
 *
 * ── Security (Decision Log 2026-05-31) ───────────────────────────────────────
 *   NEVER log: credentials, exchange objects, raw Vault values, account balances
 *   NEVER include credentialId in Error.message
 *   All logs: structured JSON, safe fields only
 *   SUPABASE_SERVICE_ROLE_KEY: Doppler only, never hardcoded
 */

import { createClient, SupabaseClient } from '@supabase/supabase-js'
import { nanoid } from 'nanoid'
import { BinanceAdapter } from './BinanceAdapter'
import { VaultSecretsProvider } from './VaultSecretsProvider'
import type { ExchangeAdapter } from './types'
import {
  BotSizingConfig,
  ExchangeAuthError,
  ExchangeAuthIpError,
  ExchangeRejectedError,
  ExchangeTimeoutError,
  ExchangeUnavailableError,
  MarketRules,
  RiskLimitExceededError,
  SizingMode,
  SizingUnavailableError,
  VaultSecretNotFoundError,
  VaultUnavailableError,
} from './types'
import {
  assertExchangeEnvironment,
  assertTradingEnabled,
  computeBuyQuantity,
  computeRequestedNotional,
  computeSellQuantity,
  isBotConfigReady,
} from './sizingRisk'
import { startHeartbeat } from './heartbeat'
import { configureAlerts, emitAlert } from './alerts'
import { startWorkerStatus } from './workerStatus'
import { startWebhookRequeueSweeper } from './webhookRequeueSweeper'
import { resolvePendingReconciliations, RECONCILIATION_RESOLVE_THRESHOLD_SECONDS } from './reconciliation'
import { startReconciliationScan } from './reconciliationScan'
import { startCredentialValidation } from './credentialValidation'
import { startProposalSweeper } from './proposalSweeper'
import { resolveEgress, productionEgressOk, egressModeLabel } from './egress'
import { credentialOwnershipOk } from './credentialOwnership'
import { SUPPORTED_EXCHANGES } from './supportedExchanges'

// ─── Config ───────────────────────────────────────────────────────────────────

const QUEUE_NAME = 'trade_signals'

/** WB1 wire-contract version this worker speaks (frozen 2026-06-04). */
const SCHEMA_VERSION = '1.0'

/**
 * Visibility timeout (seconds) — message is hidden from other consumers after
 * being read. Must exceed worst-case processing time; if processing exceeds VT, pgmq re-exposes the
 * message mid-flight (redelivery churn + spurious unknown/reconciliation — UNIQUE(bot_id,signal_id)
 * still prevents a double order, but the "read_ct stays 1" assumption breaks).
 *
 * M-16 (audit v3) — the OLD formula counted only 2 × T_exchange_timeout (createOrder + inline
 * fetchOrder) and understated the worst case. A COLD-CACHE message on a first delivery serially runs up
 * to FIVE 5s exchange calls: getMarketRules(loadMarkets) + fetchBalance + fetchPrice + createOrder +
 * inline fetchOrder, plus multiple Vault fetches + DB round-trips:
 *   worst_case ≈ 5 × T_exchange_timeout + 3 × T_vault + T_db + overhead
 *              ≈ 5 × 5000ms + ~360ms + ~200ms + ~100ms ≈ 25.7s
 *   visibility_timeout = worst_case + ~15s safety buffer ≈ 40–45s
 * So the safe DEFAULT is 45s (raised from 30s). Mitigations that shrink the worst case: warm the
 * market-rules cache at boot (removes one 5s call) and keep T_exchange_timeout ≤ 5000ms.
 *
 * The LIVE value is env-set (QUEUE_VISIBILITY_TIMEOUT_S via Doppler/Railway — an operator action); this
 * default only applies when that var is unset. See Decision Log: "pgmq visibility_timeout".
 */
const VISIBILITY_TIMEOUT_S = parseInt(process.env.QUEUE_VISIBILITY_TIMEOUT_S ?? '45', 10)

/** Poll interval when queue is empty (ms). */
const POLL_INTERVAL_MS = parseInt(process.env.POLL_INTERVAL_MS ?? '1000', 10)

/** Consecutive permanent failures before circuit breaker sets bot.status = 'error'. */
const MAX_CONSECUTIVE_FAILURES = 5

// The temporary per-symbol BUY price floors (ASSUMED_MIN_PRICE_FLOOR_USDT) were removed in
// S5-A3/B4: BUY sizing now comes from bot config + live price (sizingRisk.computeBuyQuantity)
// and fails closed — it never falls back to a floor. See docs/sprint5-s5-a3-b4-sizing-risk-design.md.

/** Trades older than this are considered stuck at boot reconciliation time. */
const RECONCILIATION_THRESHOLD_SECONDS = 60

/**
 * Canonical UUID shape — case-insensitive (gen_random_uuid() emits lowercase;
 * Postgres accepts uppercase). Validates vault_secret_id BEFORE the uuid-typed
 * get_decrypted_secret() call: a malformed pointer must fail loudly ONCE as a
 * config fault, not loop forever as a 22P02 cast error misread as transient.
 * vault.secrets.id is uuid-typed (verified live 2026-06-11), so this gate can
 * never reject a pointer that could actually resolve. (F-01)
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

// ─── Types ────────────────────────────────────────────────────────────────────

/**
 * Queue message contract (WB1 v1.0 — frozen 2026-06-04).
 * Enqueued by the WB5 Edge Function. Parsed by Worker.
 */
interface TradeSignalMessage {
  schema_version: string  // must equal SCHEMA_VERSION ('1.0') — enforced in Step 0 (F-02)
  bot_id:         string
  signal_id:      string
  side:           'buy' | 'sell'
  // 045 (optional, backward-compatible): true ONLY on the operator-approved re-enqueue of a live signal.
  // Absent on a fresh webhook signal ⇒ a LIVE bot proposes. Not part of the frozen v1.0 required-field set.
  approved?:      boolean
}

/** pgmq message envelope returned by pgmq_read() (pgmq.message_record). */
interface PgmqMessage {
  msg_id:  number
  /**
   * pgmq redelivery counter (WB7). 1 on first delivery; pgmq increments it each
   * time the visibility timeout lapses and the message is re-exposed. read_ct > 1
   * means this message was redelivered — the signal a correct VISIBILITY_TIMEOUT_S
   * must keep at 1 for every successfully-processed message (zero-duplicate redelivery).
   */
  read_ct: number
  message: TradeSignalMessage
}

/** Columns fetched from bots table in processMessage. */
interface BotRow {
  id:                   string
  user_id:              string
  credential_id:        string | null  // null = bot misconfigured (ENG-007)
  trading_pair:         string
  account_type:         string | null  // EP4: 'spot' today; the worker fail-closes on any non-spot type
  status:               string
  consecutive_failures: number
  // S5-A3/B4 sizing + risk config (migration 014). NULL = unconfigured → fail-closed.
  sizing_mode:             SizingMode | null
  position_size_pct:       number | null
  fixed_notional_usdt:     number | null
  max_order_notional_usdt: number | null
  daily_notional_cap_usdt: number | null
  trading_enabled:         boolean | null
  sell_enabled:            boolean | null
  sell_size_pct:           number | null
  // 045: StrateTeach-style execution mode. 'simulation' = arm/dry-run (no real orders); 'live' = go-live
  // (each signal is PROPOSED and needs explicit approval before it executes). null/unknown → simulation (fail-closed).
  execution_mode:          string | null
}

/** Columns fetched from user_exchange_credentials in Step 4a (F-01). */
interface CredentialRow {
  vault_secret_id:      string
  status:               string
  deleted_at:           string | null
  exchange_environment: 'testnet' | 'mainnet' | null
  user_id:              string   // A8-H3 W1: owner — must equal bot.user_id (fail-closed on mismatch)
  exchange_id:          string   // EP1b: FK to exchanges(id) — resolves the bot's venue (Step 4a.6)
}

// ─── Env validation ───────────────────────────────────────────────────────────

function validateEnv(): {
  supabaseUrl:    string
  serviceRoleKey: string
  isProduction:   boolean
  queueEnabled:   boolean
} {
  // DOPPLER_ENVIRONMENT is set by `doppler run` locally but NOT by Doppler's Railway
  // integration (which syncs secrets as plain env vars, without this key).
  // Log it if present; warn-only if absent — never block startup on its absence.
  if (process.env.DOPPLER_ENVIRONMENT) {
    console.log(JSON.stringify({
      event:       'startup_env',
      environment: process.env.DOPPLER_ENVIRONMENT, // 'dev' | 'staging' | 'production' — not a secret
    }))
  } else {
    console.log(JSON.stringify({
      event:       'startup_env',
      environment: 'unknown',
      hint:        'DOPPLER_ENVIRONMENT not set — expected on Railway (Doppler integration), warn-only in local dev',
    }))
  }

  const supabaseUrl     = process.env.SUPABASE_URL
  const serviceRoleKey  = process.env.SUPABASE_SERVICE_ROLE_KEY
  const isProductionRaw = process.env.PRAXIS_IS_PRODUCTION

  const missing = [
    !supabaseUrl      && 'SUPABASE_URL',
    !serviceRoleKey   && 'SUPABASE_SERVICE_ROLE_KEY',
    !isProductionRaw  && 'PRAXIS_IS_PRODUCTION',
  ].filter((x): x is string => typeof x === 'string')

  if (missing.length > 0) {
    console.error(JSON.stringify({ event: 'startup_error', reason: 'missing_env_vars', missing }))
    process.exit(1)
  }

  if (isProductionRaw !== 'true' && isProductionRaw !== 'false') {
    console.error(JSON.stringify({
      event:  'startup_error',
      reason: 'invalid_env_var',
      var:    'PRAXIS_IS_PRODUCTION',
      hint:   'must be exactly "true" or "false"',
    }))
    process.exit(1)
  }

  // QUEUE_ENABLED gates the poll loop (Decision 2026-06-03).
  //   Optional — absent defaults to false (safe state: Worker does not trade).
  //   Strict-if-present: a typo like "1" or "yes" must NOT silently disable
  //   trading in production, so reject anything other than "true"/"false".
  //   Default false is correct for the Sprint 2 Railway deploy: the pgmq_read
  //   RPC wrapper does not exist yet, so the poll loop would only spam
  //   queue_read_error. Set "true" in Sprint 3 once the wrapper migration lands.
  const queueEnabledRaw = process.env.QUEUE_ENABLED
  if (
    queueEnabledRaw !== undefined &&
    queueEnabledRaw !== 'true' &&
    queueEnabledRaw !== 'false'
  ) {
    console.error(JSON.stringify({
      event:  'startup_error',
      reason: 'invalid_env_var',
      var:    'QUEUE_ENABLED',
      hint:   'must be exactly "true" or "false" if set (absent → false)',
    }))
    process.exit(1)
  }

  // A1 Option B: exchange egress via a fixed-IP proxy. Acknowledge PRESENCE only (the value is a SECRET — never
  // logged). Production fail-closed is enforced per-message BEFORE building the adapter (processMessage Step 4b +
  // reconciliation defaultAdapterFor) + the BinanceAdapter constructor invariant — NOT a hard startup exit (so a
  // prod worker still boots for read-only reconciliation/observability, but never trades/egresses without a proxy).
  console.log(JSON.stringify({
    event: 'startup_env',
    exchange_proxy_configured: Boolean(process.env.EXCHANGE_HTTPS_PROXY?.trim()),
    exchange_egress_mode: egressModeLabel(resolveEgress(process.env)), // B0: 'proxy' | 'native' | 'unset'
  }))

  return {
    supabaseUrl:    supabaseUrl!,
    serviceRoleKey: serviceRoleKey!,
    isProduction:   isProductionRaw === 'true',
    queueEnabled:   queueEnabledRaw === 'true',
  }
}

// ─── Boot reconciliation ──────────────────────────────────────────────────────

/**
 * Finds trades stuck in 'pending' or 'unknown' from before this Worker instance
 * started and inserts reconciliation_jobs for triage.
 *
 * 'pending': Worker crashed after INSERT trades(pending) but before createOrder.
 *   The exchange has no order. Trade must be marked failed or re-attempted.
 *
 * 'unknown': Worker crashed after createOrder (exchange may have the order) but
 *   before UPDATE trades(submitted/filled). Must call fetchOrder to reconcile.
 *
 * Both cases require human or automated triage — reconciliation_jobs is the handoff.
 *
 * setInterval(60s) runtime scan deferred to Sprint 3.
 * See Decision Log: "Reconciliation worker — setInterval(60s) design, cap, and coordination"
 */
async function runBootReconciliation(supabase: SupabaseClient): Promise<number | null> {
  const threshold = new Date(
    Date.now() - RECONCILIATION_THRESHOLD_SECONDS * 1000,
  ).toISOString()

  const { data: stuckTrades, error } = await supabase
    .from('trades')
    .select('id, bot_id, signal_id, status')
    .in('status', ['pending', 'unknown'])
    .lt('created_at', threshold)
    .is('deleted_at', null)

  if (error) {
    console.error(JSON.stringify({
      event: 'boot_reconciliation_query_error',
      error: error.code,
    }))
    return null   // unknown — boot query failed (worker_status records null = unknown)
  }

  const count = stuckTrades?.length ?? 0
  console.log(JSON.stringify({ event: 'boot_reconciliation_complete', stuck_count: count }))

  if (count === 0) return 0

  for (const trade of stuckTrades!) {
    const { error: upsertError } = await supabase
      .from('reconciliation_jobs')
      .upsert(
        { trade_id: trade.id },
        { onConflict: 'trade_id', ignoreDuplicates: true },
      )

    if (upsertError) {
      console.error(JSON.stringify({
        event:    'reconciliation_job_upsert_error',
        trade_id: trade.id,
        status:   trade.status,
        error:    upsertError.code,
      }))
    } else {
      console.log(JSON.stringify({
        event:    'reconciliation_job_created',
        trade_id: trade.id,
        status:   trade.status,
      }))
    }
  }

  return count
}

// ─── Quantity calculation ─────────────────────────────────────────────────────
// BUY quantity is computed by sizingRisk.computeBuyQuantity (bot config + live price), wired into
// processMessage Step 6. SELL has a ready, tested helper (sizingRisk.computeSellQuantity) for the
// dedicated SELL slice; the old floor-based calculateBuyQuantity and the 95% placeholder
// calculateSellQuantity were removed (S5-A3/B4). SELL is fail-closed in Step 4b in v1 (sell off).

// H-2: the day's requested-notional sum + the per-order/daily cap check are no longer computed in the
// worker — they moved INTO the atomic reservation RPC (migration 029, public.insert_pending_trade_atomic),
// which re-checks them under a per-bot advisory lock in the same transaction as the pending INSERT. The
// reserving-status set (pending/submitted/unknown/filled) and the 00:00-UTC day boundary live in the RPC.

// ─── Audit log helper ─────────────────────────────────────────────────────────

/**
 * Inserts one row into audit_logs. Returns true on success, false on failure.
 *
 * Non-fatal BY DEFAULT: callers that ignore the return value get the historical behavior
 * (error logged, processing continues). 4A order-lifecycle hard-blockers inspect the return to
 * fail closed in live tier (never place a real order without a durable trade.created audit; never
 * silently drop a real fill's audit).
 *
 * before_state / after_state: status fields and safe metadata only.
 * Never include credentials, exchange responses, balances, or raw payloads.
 * See audit_logs schema comment — enforced by application, not DB constraint.
 *
 * actor_type is always 'worker' for Worker-originated events.
 * actor_id is null — Worker has no user identity.
 */
async function insertAuditLog(
  supabase:    SupabaseClient,
  entityType:  string,
  entityId:    string,
  eventType:   string,
  beforeState: Record<string, unknown>,
  afterState:  Record<string, unknown>,
): Promise<boolean> {
  const { error } = await supabase.from('audit_logs').insert({
    entity_type:  entityType,
    entity_id:    entityId,
    event_type:   eventType,
    before_state: beforeState,
    after_state:  afterState,
    actor_type:   'worker',
  })

  if (error) {
    console.error(JSON.stringify({
      event:       'audit_log_insert_error',
      entity_type: entityType,
      entity_id:   entityId,
      event_type:  eventType,
      error:       error.code,
    }))
    return false
  }
  return true
}

// ─── Disable credential and bot helper ───────────────────────────────────────

/**
 * Handles the immediate-disable path for permanent credential failures.
 *
 * Triggered by: VaultSecretNotFoundError | ExchangeAuthError
 * Effect:
 *   1. user_exchange_credentials.status = 'invalid' (if credential_id present)
 *   2. bots.status = 'error'
 *   3. Writes bot.disabled_credential_invalid audit event
 *
 * No consecutive_failures increment — credential failures bypass the threshold.
 * Non-fatal: individual update failures are logged but do not throw.
 * See ENG-002, ENG-003 (Decision Log 2026-06-02).
 */
async function disableCredentialAndBot(
  supabase:  SupabaseClient,
  bot:       BotRow,
  signal_id: string,
  reason:    string,
): Promise<void> {
  if (bot.credential_id) {
    const { error: credError } = await supabase
      .from('user_exchange_credentials')
      .update({ status: 'invalid' })
      .eq('id', bot.credential_id)
      .is('deleted_at', null)
    if (credError) {
      console.error(JSON.stringify({
        event:         'credential_invalidation_error',
        bot_id:        bot.id,
        credential_id: bot.credential_id,
        error:         credError.code,
      }))
    }
  }

  const { error: botError } = await supabase
    .from('bots')
    .update({ status: 'error' })
    .eq('id', bot.id)
  if (botError) {
    console.error(JSON.stringify({
      event:  'bot_disable_error',
      bot_id: bot.id,
      error:  botError.code,
    }))
  }

  await insertAuditLog(
    supabase, 'bot', bot.id, 'bot.disabled_credential_invalid',
    { status: bot.status },
    { status: 'error', reason },
  )
  console.error(JSON.stringify({
    event:     'bot_disabled_credential_invalid',
    bot_id:    bot.id,
    signal_id,
    reason,
  }))
  emitAlert('credential_invalidated', { bot_id: bot.id, signal_id, reason }) // Plan v1.1 · 1.5 — operator-actionable (no-op unless ALERT_WEBHOOK_URL set)
}

/**
 * Auth-ATTENTION pause (mainnet -2015 handling, Plan v1.1 · 1.1). A ccxt -2015 ("invalid key, IP, or
 * permissions") is AMBIGUOUS — most often, on mainnet, a GOOD IP-allowlisted key called from an egress IP
 * not yet on its allowlist. We must NOT brand the credential 'invalid' (disableCredentialAndBot) off that
 * infra/allowlist condition. Instead fail-closed by PAUSING the bot (disarm) WITHOUT touching
 * credential.status, and surface an operator-actionable audit so the operator verifies the key's IP allowlist
 * + trade permission, then re-arms. credential.status stays whatever it was (typically 'valid').
 */
async function pauseBotForAuthAttention(
  supabase:  SupabaseClient,
  bot:       BotRow,
  signal_id: string,
  reason:    string,
): Promise<void> {
  const { error: botError } = await supabase
    .from('bots')
    .update({ trading_enabled: false, status: 'paused' })
    .eq('id', bot.id)
  if (botError) {
    console.error(JSON.stringify({ event: 'bot_pause_auth_attention_error', bot_id: bot.id, error: botError.code }))
  }
  await insertAuditLog(
    supabase, 'bot', bot.id, 'bot.paused_auth_attention',
    { status: bot.status },
    { status: 'paused', reason },
  )
  console.error(JSON.stringify({ event: 'bot_paused_auth_attention', bot_id: bot.id, signal_id, reason }))
  emitAlert('auth_attention_pause', { bot_id: bot.id, signal_id, reason }) // Plan v1.1 · 1.5 — mainnet IP/permission attention (no-op unless ALERT_WEBHOOK_URL set)
}

// ── Execution-mode (045): StrateTeach-style arm=simulation / go-live=per-order approval. The Praxis money
//    path (insert_pending_trade_atomic + createOrder + every gate) is UNCHANGED — only SIMULATION and
//    LIVE-propose STOP before it; an APPROVED live order runs the existing path 1:1. ────────────────────
const APPROVAL_TTL_MS = Number(process.env.PROPOSAL_APPROVAL_TTL_MS ?? 15 * 60_000) // un-approved proposals auto-expire (fail-safe)

/** SIMULATION (arm): record a simulated fill — a trade row marked simulated=true, NEVER sent to the exchange.
 *  Uses the live signal price so the user's simulated P&L is realistic. Best-effort; never throws. */
async function recordSimulatedFill(
  supabase: SupabaseClient,
  t: { botId: string; userId: string; signalId: string; side: 'buy' | 'sell'; tradingPair: string; quantity: number; price: number; requestedNotional: number | null },
): Promise<void> {
  const notional = t.price > 0 ? t.price * t.quantity : 0
  const { error } = await supabase.from('trades').insert({
    bot_id: t.botId, user_id: t.userId, signal_id: t.signalId,
    client_order_id: `SIM_${nanoid(10)}`,
    side: t.side, trading_pair: t.tradingPair, quantity: t.quantity,
    price_at_signal: t.price > 0 ? t.price : null, price_at_execution: t.price > 0 ? t.price : null,
    requested_notional_usdt: t.requestedNotional ?? 0, executed_notional_usdt: notional,
    status: 'filled', simulated: true,
  })
  if (error) console.error(JSON.stringify({ event: 'sim_fill_insert_error', bot_id: t.botId, signal_id: t.signalId, error: error.code }))
}

/** LIVE fresh signal: record a PROPOSED order awaiting the user's Approve/Reject. NEVER places an order.
 *  Idempotent on (bot,signal) — a pgmq redelivery just conflicts (23505) and is ignored. */
async function proposeOrder(
  supabase: SupabaseClient,
  t: { botId: string; userId: string; signalId: string; side: 'buy' | 'sell'; tradingPair: string; requestedNotional: number | null; price: number },
): Promise<void> {
  const { error } = await supabase.from('proposed_trades').insert({
    bot_id: t.botId, user_id: t.userId, signal_id: t.signalId,
    side: t.side, trading_pair: t.tradingPair,
    requested_notional_usdt: t.requestedNotional, price_at_signal: t.price > 0 ? t.price : null,
    status: 'pending', expires_at: new Date(Date.now() + APPROVAL_TTL_MS).toISOString(),
  })
  if (error && error.code !== '23505') console.error(JSON.stringify({ event: 'propose_insert_error', bot_id: t.botId, signal_id: t.signalId, error: error.code }))
}

// ─── Misconfigured-bot helper (F-01) ─────────────────────────────────────────

/**
 * Fail-closed bot disable for credential CONFIGURATION faults: row missing,
 * soft-deleted, status not 'valid', or corrupt vault_secret_id pointer.
 *
 * The credential row is NEVER touched here. Config/wiring/data faults must not
 * brand a possibly-healthy exchange key 'invalid' — that verdict is reserved
 * for disableCredentialAndBot(), which fires only on proven-dead credentials
 * (VaultSecretNotFoundError / ExchangeAuthError AFTER correct resolution).
 * F-01 ratification, 2026-06-11.
 */
async function disableBotMisconfigured(
  supabase:  SupabaseClient,
  bot:       BotRow,
  signal_id: string,
  reason:    string,
): Promise<void> {
  const { error: botError } = await supabase
    .from('bots')
    .update({ status: 'error' })
    .eq('id', bot.id)
  if (botError) {
    console.error(JSON.stringify({
      event:  'bot_disable_error',
      bot_id: bot.id,
      error:  botError.code,
    }))
  }
  await insertAuditLog(
    supabase, 'bot', bot.id, 'bot.misconfigured',
    { status: bot.status },
    { status: 'error', reason },
  )
  console.error(JSON.stringify({
    event:  'bot_misconfigured_credential',
    bot_id: bot.id,
    signal_id,
    reason,
  }))
}

// ─── processMessage ───────────────────────────────────────────────────────────

// A per-message adapter factory. The DEFAULT constructs the real BinanceAdapter with all egress
// args threaded from the resolved config. It is injectable ONLY by tests — no production caller
// passes `deps` (the binance-adapter-callsites guard asserts every non-test processMessage() call
// has ≤2 args), so there is no runtime path to construct an adapter with a non-real isProduction/
// egress under production. Mirrors reconciliation.ts's ResolveDeps.adapterFor pattern.
type AdapterFactory = (
  secretsProvider: VaultSecretsProvider,
  vaultSecretId: string,
  isProduction: boolean,
  exchangeHttpsProxy: string | null,
  nativeEgressAllowed: boolean,
  exchangeId: string,
) => ExchangeAdapter

interface ProcessMessageDeps {
  adapterFactory?: AdapterFactory
  /** EP7: injectable clock for deterministic latency-instrumentation tests. Defaults to Date.now. */
  now?: () => number
}

/**
 * Executes the full trade pipeline for one queue message.
 *
 * Returns { ack: true }  → caller deletes the message from pgmq (permanent outcome).
 * Returns { ack: false } → caller does NOT ack; visibility timeout re-exposes it.
 */
async function processMessage(
  supabase: SupabaseClient,
  msg:      PgmqMessage,
  deps:     ProcessMessageDeps = {},
): Promise<{ ack: boolean }> {

  // ── Step 0: Validate message shape (WB1 v1.0) ───────────────────────────────
  const raw = msg.message
  if (
    !raw ||
    typeof raw.bot_id    !== 'string' || raw.bot_id.length    === 0 ||
    typeof raw.signal_id !== 'string' || raw.signal_id.length === 0 ||
    (raw.side !== 'buy' && raw.side !== 'sell')
  ) {
    console.error(JSON.stringify({
      event:  'invalid_message_shape',
      msg_id: msg.msg_id,
      reason: 'bad_fields',
    }))
    return { ack: true } // malformed — ack, retrying cannot fix this
  }

  // schema_version gate (F-02): only the frozen v1.0 contract is executable.
  // A future v2 message must be rejected loudly here, never silently run as v1.
  if (raw.schema_version !== SCHEMA_VERSION) {
    console.error(JSON.stringify({
      event:          'invalid_message_shape',
      msg_id:         msg.msg_id,
      reason:         'unsupported_schema_version',
      schema_version: typeof raw.schema_version === 'string' ? raw.schema_version : null,
    }))
    return { ack: true } // wrong contract version — ack; retrying cannot fix
  }

  const { bot_id, signal_id, side } = raw
  // 045: 'approved' is set ONLY by the operator's Approve action (the approve-order Edge re-enqueues the
  // signal with approved:true). A fresh webhook signal omits it ⇒ a LIVE bot PROPOSES and waits. The queue is
  // the trust boundary (only the token-authed webhook + the ownership-checked approve Edge can enqueue), and
  // idempotency (Step 2/3) dedups a redelivered approved message so it can never place a second order.
  const approved = raw.approved === true

  // EP7: per-stage latency instrumentation (logging-only, no behavior change). Marks are stamped at
  // stage boundaries and emitted as a `trade_timing` event ONLY on the success path (an order placed),
  // so the operator/latency analysis can see where worker-side wall-clock goes — dominated by the
  // exchange round-trips. The webhook→enqueue→dequeue legs live outside the worker (Phase 2B M5 adds
  // end-to-end timing across the boundary). now() is injectable so the timing itself is testable.
  const now = deps.now ?? (() => Date.now())
  const timing: Record<string, number> = { start: now() }

  // ── Step 1: Fetch bot ────────────────────────────────────────────────────────
  const { data: botData, error: botError } = await supabase
    .from('bots')
    .select('id, user_id, credential_id, trading_pair, account_type, status, consecutive_failures, sizing_mode, position_size_pct, fixed_notional_usdt, max_order_notional_usdt, daily_notional_cap_usdt, trading_enabled, sell_enabled, sell_size_pct, execution_mode')
    .eq('id', bot_id)
    .is('deleted_at', null)
    .single()

  if (botError || !botData) {
    console.error(JSON.stringify({
      event:     'bot_not_found',
      bot_id,
      signal_id,
      error:     botError?.code ?? 'no_row',
    }))
    return { ack: true } // bot doesn't exist — retrying cannot help
  }

  const bot = botData as BotRow

  // ── Step 2: Check bot is active ──────────────────────────────────────────────
  if (bot.status !== 'active') {
    console.log(JSON.stringify({
      event:      'bot_not_active',
      bot_id,
      signal_id,
      bot_status: bot.status,
    }))
    return { ack: true } // paused / error / deleted — skip, no retry
  }

  // ── Step 2.5: Guard — null credential (ENG-007) ─────────────────────────────
  // Active bot with no credential_id is a misconfiguration — cannot trade.
  // Disable immediately; operator must re-attach credentials to re-activate.
  if (!bot.credential_id) {
    await supabase.from('bots').update({ status: 'error' }).eq('id', bot.id)
    await insertAuditLog(
      supabase, 'bot', bot.id, 'bot.misconfigured',
      { status: bot.status },
      { status: 'error', reason: 'credential_id_null' },
    )
    console.error(JSON.stringify({
      event:     'bot_misconfigured_no_credential',
      bot_id,
      signal_id,
    }))
    return { ack: true }
  }

  // ── Step 3: Idempotency check ────────────────────────────────────────────────
  // Step 0b (crash recovery via fetchOrder) is deferred to Sprint 3.
  // On 'unknown' trade: upsert reconciliation_job so triage is not delayed further.
  // On any terminal status: log duplicate and ack cleanly.
  // See Decision Log: "processMessage step 0b — crash recovery"
  const { data: existingTrade } = await supabase
    .from('trades')
    .select('id, status')
    .eq('bot_id', bot_id)
    .eq('signal_id', signal_id)
    .maybeSingle()

  if (existingTrade) {
    if (existingTrade.status === 'unknown') {
      // Signal re-queued while prior trade is still unresolved.
      // Ensure a reconciliation_job exists for triage; then ack.
      const { error: reconError } = await supabase
        .from('reconciliation_jobs')
        .upsert({ trade_id: existingTrade.id }, { onConflict: 'trade_id', ignoreDuplicates: true })
      if (reconError) {
        console.error(JSON.stringify({
          event:    'reconciliation_job_upsert_error_on_requeue',
          trade_id: existingTrade.id,
          bot_id,
          signal_id,
          error:    reconError.code,
        }))
      }
      console.log(JSON.stringify({
        event:    'unknown_trade_requeued',
        trade_id: existingTrade.id,
        bot_id,
        signal_id,
      }))
    } else {
      console.log(JSON.stringify({
        event:        'duplicate_signal',
        bot_id,
        signal_id,
        trade_id:     existingTrade.id,
        trade_status: existingTrade.status,
      }))
    }
    return { ack: true }
  }

  // ── Step 3.5: Guard — block on any UNRESOLVED trade for this bot (ENG-004, H-1) ──────────
  // We cannot safely issue a NEW order while a prior order's outcome is ambiguous — we don't know the
  // real position. Two ambiguous states block:
  //   • status='unknown'          — resolution is deferred to reconciliation (any age).
  //   • status='pending' AND stale — a crash (SIGKILL/OOM/redeploy) BETWEEN the pending INSERT and the
  //     status update leaves a 'pending' row whose order may be live (H-1). A DIFFERENT signal arriving
  //     within the boot-reconciliation window would otherwise NOT be blocked (UNIQUE(bot_id,signal_id)
  //     only stops the SAME signal), so it could place a SECOND real order → double position.
  // "Stale" = older than the reconciliation threshold, so a normal in-flight order (a fresh 'pending'
  // that this very message could be racing) is NOT falsely blocked; only crash-orphaned ones are.
  // Block by returning ack=false: the message stays queued until the ambiguous trade is resolved.
  // Fail-safe: a DB query error also blocks (unknown truth = unsafe to trade).
  const stalePendingCutoffIso = new Date(
    Date.now() - RECONCILIATION_RESOLVE_THRESHOLD_SECONDS * 1000,
  ).toISOString()
  const { count: blockingCount, error: blockingQueryError } = await supabase
    .from('trades')
    .select('id', { count: 'exact', head: true })
    .eq('bot_id', bot_id)
    .is('deleted_at', null)
    .or(`status.eq.unknown,and(status.eq.pending,created_at.lt.${stalePendingCutoffIso})`)

  if (blockingQueryError || (blockingCount ?? 0) > 0) {
    console.log(JSON.stringify({
      event:          'bot_blocked_unresolved_trades',
      bot_id,
      signal_id,
      blocking_count: blockingQueryError ? 'query_error' : blockingCount,
      reason:         'unknown_or_stale_pending',
    }))
    return { ack: false }
  }

  // ── Step 4a: Resolve credential row → Vault pointer (F-01) ──────────────────
  // bots.credential_id is a FK to user_exchange_credentials.id — NOT a Vault id.
  // The Vault pointer is user_exchange_credentials.vault_secret_id, which moves
  // independently under key rotation (migration 005). Passing credential_id to
  // get_decrypted_secret() can never resolve and would falsely fire the
  // Branch-1 disable on a healthy credential.
  // bot.credential_id is guaranteed non-null here — Step 2.5 guards the null case.
  const { data: credData, error: credError } = await supabase
    .from('user_exchange_credentials')
    .select('vault_secret_id, status, deleted_at, exchange_environment, user_id, exchange_id')
    .eq('id', bot.credential_id)
    .maybeSingle()

  if (credError) {
    // Infra fault — credential truth unknown. Touch nothing; retry via
    // visibility timeout. A config fault must never be invented from an outage.
    console.error(JSON.stringify({
      event:     'credential_fetch_error',
      bot_id,
      signal_id,
      error:     credError.code,
    }))
    return { ack: false }
  }

  const cred = credData as CredentialRow | null

  if (!cred || cred.deleted_at !== null || cred.status !== 'valid') {
    // Misconfiguration — fail closed: bot → error; credential row untouched
    // (its own status already tells the truth; see disableBotMisconfigured).
    const reason =
      !cred                      ? 'credential_row_missing'
      : cred.deleted_at !== null ? 'credential_deleted'
      :                            `credential_status_${cred.status}`
    await disableBotMisconfigured(supabase, bot, signal_id, reason)
    return { ack: true }
  }

  // ── Step 4a.5: Guard — credential OWNERSHIP (A8-H3 W1) ──────────────────────
  // Fail closed if the resolved credential is not owned by this bot's user. Belt-and-suspenders
  // with the DB composite FK (migration 021): the worker refuses to decrypt or build an adapter
  // for a cross-user credential. No decrypt, no adapter, no Vault delete — only THIS bot disabled;
  // logs carry only ids + reason (never vault_secret_id or any secret).
  if (!credentialOwnershipOk(cred.user_id, bot.user_id)) {
    await disableBotMisconfigured(supabase, bot, signal_id, 'credential_owner_mismatch')
    return { ack: true }
  }

  if (typeof cred.vault_secret_id !== 'string' || !UUID_RE.test(cred.vault_secret_id)) {
    // Corrupt stored pointer = server-side config/data fault (HASH_RE doctrine).
    // A non-UUID pointer can never resolve in vault.secrets (uuid PK) — fail
    // loudly once; never loop as 'transient'. Supersedes the prior
    // 'malformed vault_secret_id → VaultUnavailableError → transient' mapping
    // (ratified 2026-06-11; Decision Log note at WB6 closeout).
    await disableBotMisconfigured(supabase, bot, signal_id, 'vault_secret_id_malformed')
    return { ack: true }
  }

  // ── Step 4a.6: Resolve the credential's exchange + fail-closed venue gate (EP1b) ────────────
  // The bot's venue IS the credential's exchange (structural: the adapter and the API key come from
  // the SAME exchanges row, so a Binance key can never drive, say, a Bybit adapter). TWO independent
  // gates must BOTH pass before an adapter is built:
  //   (1) exchanges.is_active = true — the operator's per-venue activation switch (every venue except
  //       binance seeds inactive; migrations 001/037), and
  //   (2) exchanges.ccxt_id ∈ SUPPORTED_EXCHANGES — the worker's code-proven allowlist.
  // Either failing ⇒ fail-closed, bot disabled (config fault), credential row untouched. A fetch
  // ERROR is infra (venue truth unknown) ⇒ retry via visibility timeout, invent nothing — mirroring
  // the Step 4a credError doctrine. Ordered BEFORE Step 4b so a dormant/unsupported venue blocks
  // before any Exchange call.
  const { data: exData, error: exError } = await supabase
    .from('exchanges')
    .select('ccxt_id, is_active')
    .eq('id', cred.exchange_id)
    .maybeSingle()

  if (exError) {
    console.error(JSON.stringify({
      event:     'exchange_fetch_error',
      bot_id,
      signal_id,
      error:     exError.code,
    }))
    return { ack: false }
  }

  const ex = exData as { ccxt_id: string; is_active: boolean } | null
  if (!ex || ex.is_active !== true || !SUPPORTED_EXCHANGES.has(ex.ccxt_id)) {
    const reason =
      !ex                       ? 'exchange_row_missing'
      : ex.is_active !== true   ? 'exchange_inactive'
      :                           'exchange_unsupported'
    await disableBotMisconfigured(supabase, bot, signal_id, reason)
    return { ack: true }
  }
  const exchangeId = ex.ccxt_id

  // ── Step 4b: Size config + policy gates — fail-closed BEFORE building the adapter or any
  // Exchange call (gate ordering). A disabled bot, incomplete config, or a testnet/mainnet
  // mismatch must block HERE, before getMarketRules (public exchange) / fetchBalance / fetchPrice
  // ever run — otherwise a blocked bot's outcome would hang on a public Exchange call (a transient
  // failure there would retry instead of blocking). SELL is blocked in v1 before adapter
  // construction; the dedicated SELL slice will wire computeSellQuantity through the same gates.
  // botSizing + onSizingError are reused by the Step 6 BUY sizing below.
  const isProduction = process.env.PRAXIS_IS_PRODUCTION === 'true'
  // A1 (B0): explicit exchange-egress model — proxy (EXCHANGE_HTTPS_PROXY) OR native static IPs
  // (EXCHANGE_EGRESS_MODE=native). In production exactly one must be configured (else fail-closed below).
  const egress = resolveEgress(process.env)
  const exchangeHttpsProxy = egress.proxy
  // 4A: order-lifecycle audit fail-closed. Engages ONLY in live tier AND when explicitly enabled
  // (flag default OFF for a dark rollout). Testnet is never affected → ergonomics preserved.
  const auditFailClosed = isProduction && process.env.AUDIT_FAIL_CLOSED_ENABLED === 'true'
  const botSizing: BotSizingConfig = {
    sizing_mode:             bot.sizing_mode ?? null,
    position_size_pct:       bot.position_size_pct ?? null,
    fixed_notional_usdt:     bot.fixed_notional_usdt ?? null,
    max_order_notional_usdt: bot.max_order_notional_usdt ?? null,
    daily_notional_cap_usdt: bot.daily_notional_cap_usdt ?? null,
    trading_enabled:         bot.trading_enabled ?? false,
    sell_enabled:            bot.sell_enabled ?? false,
    sell_size_pct:           bot.sell_size_pct ?? null,
  }

  // Map a sizing/risk throw to ack semantics: a policy/config block is permanent (ack, NO order,
  // NO pending trade) and is recorded as an auditable bot-scoped 'order.blocked' event; anything
  // unexpected (e.g. the daily-cap query failing) is transient (retry, no audit — it is not a
  // decision). `reason` is a non-secret label. There is no trade row for a blocked order, so the
  // audit attaches to the bot (entity_id = bot_id).
  const onSizingError = async (e: unknown, where: string): Promise<{ ack: boolean }> => {
    if (e instanceof SizingUnavailableError || e instanceof RiskLimitExceededError) {
      const kind   = e.constructor.name
      const reason = (e as { reason: string }).reason
      await insertAuditLog(
        supabase, 'bot', bot_id, 'order.blocked',
        {},
        { signal_id, side, reason, kind, where },
      )
      console.error(JSON.stringify({
        event:  'order_blocked',
        bot_id,
        signal_id,
        side,
        kind,
        reason,
        where,
      }))
      return { ack: true }
    }
    console.error(JSON.stringify({
      event:  'sizing_error',
      bot_id,
      signal_id,
      where,
      error:  e instanceof Error ? e.constructor.name : 'unknown',
    }))
    return { ack: false }
  }

  // ── Step 4b: Policy gates — fail-closed BEFORE the adapter / getMarketRules / any Exchange call.
  // Kill switch + env guard + egress apply to BOTH sides: a disabled or environment-mismatched bot,
  // or an unconfigured production egress, must neither BUY nor SELL. BUY additionally requires full
  // sizing-config readiness HERE; SELL defers ITS readiness (sell_enabled + sell_size_pct) to
  // computeSellQuantity in Step 6, so a sell-only bot is never forced to carry BUY sizing config.
  //
  // EP3: SELL is now routed through these SAME gates (previously it was fail-closed OFF in v1). SELL
  // remains a deliberate per-bot opt-in — a bot with sell_enabled=false (the default) has every exit
  // signal blocked+audited at Step 6 via computeSellQuantity('sell_not_enabled'), so enabling exits
  // is an explicit operator action, never automatic.
  try {
    // EP4 (futures cage): the whole live path — sizing, caps, createOrder — is SPOT semantics. A bot
    // whose account_type is anything other than 'spot' (i.e. a future 'futures') MUST NOT be silently
    // executed as a spot market order; fail-closed here, before the adapter, until the futures
    // execution path (mandatory per-order leverage, isolated margin, reduce-only exits, exposure-based
    // caps, futures testnet — a separately-gated slice) is wired. 'spot' and null (legacy) proceed.
    if (bot.account_type != null && bot.account_type !== 'spot') {
      throw new SizingUnavailableError('account_type_not_supported')
    }
    assertTradingEnabled(botSizing)                                   // kill switch (both sides)
    assertExchangeEnvironment(isProduction, cred.exchange_environment) // testnet/mainnet guard (both sides)
    // Mainnet GLOBAL master-switch (Plan v1.1 · 1.2). Even a fully-armed mainnet bot is fail-closed the instant
    // the operator flips PRAXIS_MAINNET_ENABLED off — the worker refuses EVERY mainnet order until it is
    // explicitly "true". Independent of the Edge per-user approval (which gates arm-time); this is the runtime
    // global kill for real-money execution. Testnet is unaffected.
    if (cred.exchange_environment === 'mainnet'
        && (process.env.PRAXIS_MAINNET_ENABLED ?? '').trim().toLowerCase() !== 'true') {
      throw new SizingUnavailableError('mainnet_master_switch_off')
    }
    // MED-1 (pre-multi-user follow-up): this checks only the GLOBAL switch. Per-user revocation via
    // mainnet_approvals.active=false is enforced at the Edge (new connect/validate/arm), and for a single
    // approved user the global switch + pause-bot are effective kills. BEFORE a 2nd real-money user, add a
    // per-order `mainnet_approvals.active` re-check for cred.user_id here (fail-closed) so one user can be
    // revoked at runtime without killing everyone.
    // A1 (B0): in production, egress must be EXPLICITLY configured — a proxy OR native static egress. An
    // unconfigured egress is a fail-closed config fault — BLOCK here, BEFORE constructing the adapter.
    // Native mode = direct egress via Railway's static outbound IPs (no proxy passed to ccxt).
    if (!productionEgressOk(isProduction, egress)) {
      throw new SizingUnavailableError('exchange_egress_unconfigured')
    }
    if (side === 'buy' && !isBotConfigReady(botSizing, cred.exchange_environment).ready) {
      throw new SizingUnavailableError('config_incomplete')
    }
    if (side === 'sell' && !(botSizing.sell_enabled ?? false)) {
      // SELL is a per-bot opt-in. A bot WITHOUT sell_enabled blocks HERE — before the adapter and any
      // exchange call — so an exit is never even priced for a bot the operator has not explicitly
      // enabled for selling. computeSellQuantity re-checks this (defense-in-depth), but gating early
      // avoids a wasted balance read and matches the "no adapter for a blocked bot" property.
      throw new SizingUnavailableError('sell_not_enabled')
    }
  } catch (e) {
    return await onSizingError(e, 'gates')
  }

  // ── Step 4: Build adapter ────────────────────────────────────────────────────
  // Step 4b gates above already ran (env/egress/config/kill) BEFORE this point. The default factory
  // builds the real adapter with the real isProduction/egress args; a test may inject
  // deps.adapterFactory to drive the full path against a stub. The `new BinanceAdapter(` literal
  // stays here (6 args — the callsites guard requires ≥5, the egress args; the 6th is the resolved
  // venue). No prod caller passes deps. `exchangeId` was resolved + double-gated in Step 4a.6.
  const secretsProvider = new VaultSecretsProvider(supabase)
  const buildAdapter: AdapterFactory = deps.adapterFactory ??
    ((sp, vsid, prod, proxy, native, exId) => new BinanceAdapter(sp, vsid, prod, proxy, native, exId))
  const adapter         = buildAdapter(secretsProvider, cred.vault_secret_id, isProduction, exchangeHttpsProxy, egress.nativeAllowed, exchangeId)
  timing.adapterReady = now()   // EP7: end of setup / start of exchange I/O

  // ── Step 5: Get market rules ─────────────────────────────────────────────────
  // symbol from bots.trading_pair — never from queue message (Option A, 2026-06-01)
  let rules: MarketRules
  try {
    rules = await adapter.getMarketRules(bot.trading_pair)
  } catch (e) {
    console.error(JSON.stringify({
      event:  'market_rules_error',
      bot_id,
      signal_id,
      error:  e instanceof Error ? e.constructor.name : 'unknown',
      detail: e instanceof ExchangeUnavailableError ? e.detail : undefined, // WB6: original cause (non-secret)
    }))
    return { ack: false } // transient — retry via visibility timeout
  }

  // ── Step 6: Size the order + enforce risk (S5-A3/B4) ─────────────────────────
  // "The code is the guardrail; the DB config is the policy." For BUY, the policy gates already
  // ran in Step 4b (kill switch / env / config readiness) BEFORE any Exchange call; here we read
  // live market data, size from config, and enforce the server-side caps. requested_notional_usdt
  // is stored on the pending row and is the daily-cap reservation basis (never recomputed from a
  // later price). A sizing/risk block here is recorded via onSizingError as a bot-scoped
  // 'order.blocked' audit row (no trade row is created for a blocked order).
  let quantity: number
  let requestedNotionalUsdt: number | null = null

  // Read live market data. BUY sizes off free QUOTE balance + live price; SELL (EP3) sizes off free
  // BASE balance (the exchange balance IS the position — no price needed). The credential-invalid vs
  // transient handling is shared. (Policy gates passed in Step 4b.)
  const baseAsset  = rules.symbol.split('/')[0]   // 'BTC/USDT' → 'BTC'
  const quoteAsset = rules.symbol.split('/')[1]   // 'BTC/USDT' → 'USDT'
  let freeQuote = 0
  let freeBase  = 0
  let price     = 0
  try {
    const balance = await adapter.fetchBalance()
    if (side === 'buy') {
      freeQuote = balance[quoteAsset]?.free ?? 0
      price     = await adapter.fetchPrice(rules.symbol)
    } else {
      freeBase  = balance[baseAsset]?.free ?? 0
    }
  } catch (e) {
    if (e instanceof ExchangeAuthIpError) {
      // -2015 ambiguous (mainnet): PAUSE (disarm) the bot, do NOT invalidate the key — could be a good key
      // from a not-yet-allowlisted egress IP. No trade row yet → ack, no DLQ. Operator fixes IP/perm + re-arms.
      await pauseBotForAuthAttention(supabase, bot, signal_id, 'ip_or_permission')
      console.error(JSON.stringify({ event: `${side}_market_data_auth_ip`, bot_id, signal_id }))
      return { ack: true }
    }
    if (e instanceof VaultSecretNotFoundError || e instanceof ExchangeAuthError) {
      // Permanent credential failure before any trade was created — disable, no DLQ, ack.
      const errorName = e instanceof Error ? e.constructor.name : 'unknown'
      await disableCredentialAndBot(supabase, bot, signal_id, errorName)
      console.error(JSON.stringify({ event: `${side}_market_data_credential_invalid`, bot_id, signal_id, error: errorName }))
      return { ack: true }
    }
    // Transient (timeout / unavailable / vault outage). No trade row yet — safe to retry.
    console.error(JSON.stringify({
      event:  `${side}_market_data_error`,
      bot_id,
      signal_id,
      error:  e instanceof Error ? e.constructor.name : 'unknown',
      detail: e instanceof ExchangeUnavailableError ? e.detail : undefined, // non-secret
      code:   e instanceof VaultUnavailableError ? e.code : undefined,
    }))
    return { ack: false }
  }

  // ── Size from config + live data (exchange min-size + non-finite guards only). ──
  // BUY: the per-order + daily caps and the pending-row INSERT are done ATOMICALLY in one DB call
  // (Step 7, H-2) under a per-bot advisory lock. computeBuyQuantity still enforces the exchange
  // min-qty/min-notional and non-finite guards HERE (the RPC does not know market rules), so
  // below_min_* still blocks pre-RPC.
  // SELL (EP3): size = sell_size_pct% of free BASE, rounded DOWN to step. computeSellQuantity throws
  // sell_not_enabled / missing_sell_size_pct / invalid_free_base (→ onSizingError: order.blocked +
  // ack), and returns NULL when the rounded qty is below minQty — i.e. NO sellable position: ack +
  // skip (a benign no-op, not a failure; no trade row). Exits carry NO requested_notional and are
  // EXEMPT from the daily BUY cap (an exit must always be allowed to reduce exposure).
  try {
    if (side === 'buy') {
      quantity              = computeBuyQuantity(botSizing, rules, price, freeQuote)
      requestedNotionalUsdt = computeRequestedNotional(botSizing, freeQuote)
    } else {
      const sellQty = computeSellQuantity(botSizing, rules, freeBase)
      if (sellQty === null) {
        await insertAuditLog(supabase, 'bot', bot_id, 'order.skipped',
          {}, { signal_id, side, reason: 'no_sellable_position' })
        console.log(JSON.stringify({ event: 'sell_skipped_no_position', bot_id, signal_id }))
        return { ack: true }
      }
      quantity              = sellQty
      requestedNotionalUsdt = null
    }
  } catch (e) {
    return await onSizingError(e, 'sizing')
  }

  // ── Execution mode (045) — StrateTeach-style. SIMULATION and un-approved LIVE both STOP here, BEFORE the
  //    money-path; only an APPROVED live order continues to Step 7 (reserve + createOrder), byte-identical to
  //    today. Sizing above ran identically for all modes, so the simulated/proposed order is realistic.
  const execMode = bot.execution_mode === 'live' ? 'live' : 'simulation' // fail-closed: anything not 'live' ⇒ simulation
  if (execMode === 'simulation') {
    await recordSimulatedFill(supabase, { botId: bot_id, userId: bot.user_id, signalId: signal_id, side, tradingPair: bot.trading_pair, quantity, price, requestedNotional: requestedNotionalUsdt })
    await insertAuditLog(supabase, 'bot', bot_id, 'order.simulated', {}, { signal_id, side, quantity, simulated: true })
    console.log(JSON.stringify({ event: 'sim_fill', bot_id, signal_id, side, quantity }))
    return { ack: true }
  }
  if (!approved) {
    // LIVE but not yet approved → propose it and WAIT for the user. No reservation, no order.
    await proposeOrder(supabase, { botId: bot_id, userId: bot.user_id, signalId: signal_id, side, tradingPair: bot.trading_pair, requestedNotional: requestedNotionalUsdt, price })
    await insertAuditLog(supabase, 'bot', bot_id, 'order.proposed', {}, { signal_id, side })
    console.log(JSON.stringify({ event: 'order_proposed', bot_id, signal_id, side }))
    return { ack: true }
  }
  // LIVE + APPROVED → fall through to the real order path below, unchanged.

  // ── Step 7: reserve the pending trade BEFORE createOrder (crash-recovery invariant). ──────────────
  const clientOrderId = `PRX_${nanoid(10)}`
  let tradeId: string

  if (side === 'buy') {
    // BUY: ATOMIC reservation — per-order + daily cap re-check + pending INSERT in one txn (H-2).
    // Decision Log 2026-05-20: the RPC (migration 029) takes a per-bot advisory lock, re-checks the
    // caps against the day's running sum, and inserts — so concurrent signals can never both pass the
    // cap. Caps are guaranteed non-null here (Step 4b config-readiness); the RPC's 'invalid_input' is a
    // defensive backstop. requested_notional_usdt is stored by the RPC (the daily-cap reservation basis).
    const { data: reservationData, error: reserveError } = await supabase.rpc('insert_pending_trade_atomic', {
      p_bot_id:             bot_id,
      p_user_id:            bot.user_id,
      p_signal_id:          signal_id,
      p_client_order_id:    clientOrderId,
      p_side:               side,
      p_trading_pair:       bot.trading_pair,
      p_quantity:           quantity,
      p_requested_notional: requestedNotionalUsdt,
      p_max_order_notional: botSizing.max_order_notional_usdt,
      p_daily_cap:          botSizing.daily_notional_cap_usdt,
    })

    if (reserveError) {
      // Infra fault calling the reservation RPC — no reservation happened. Transient: retry via the
      // visibility timeout. NO order, NO trade row. (A missing RPC surfaces here as PGRST202.)
      console.error(JSON.stringify({
        event:  'reservation_rpc_error',
        bot_id,
        signal_id,
        error:  (reserveError as { code?: string }).code ?? 'rpc_error',
      }))
      return { ack: false }
    }

    // A table-returning function yields an array of rows via PostgREST.
    const reservation = (Array.isArray(reservationData) ? reservationData[0] : reservationData) as
      { trade_id: string | null; rejected_reason: string | null } | null
    const rejectedReason = reservation?.rejected_reason ?? null
    const reservedTradeId = reservation?.trade_id ?? null

    if (rejectedReason !== null) {
      if (rejectedReason === 'duplicate_signal') {
        // A concurrent worker already reserved this (bot_id, signal_id). Dedup: ack, no order, no block audit.
        console.error(JSON.stringify({ event: 'duplicate_signal_race', bot_id, signal_id, error: '23505' }))
        return { ack: true }
      }
      // per_order_max_notional / daily_notional_cap / invalid_input: a permanent policy/config block —
      // NO order, NO trade row (the RPC inserted nothing). Record the SAME bot-scoped order.blocked audit
      // as the sizing/risk gates so alerting/triage stays consistent. `reason` is a non-secret label.
      await insertAuditLog(
        supabase, 'bot', bot_id, 'order.blocked',
        {},
        { signal_id, side, reason: rejectedReason, kind: 'AtomicReservation', where: 'reservation' },
      )
      console.error(JSON.stringify({ event: 'order_blocked', bot_id, signal_id, side, kind: 'AtomicReservation', reason: rejectedReason, where: 'reservation' }))
      return { ack: true }
    }

    if (reservedTradeId === null) {
      // Defensive: no rejection AND no trade_id (should never happen) — treat as transient, no order.
      console.error(JSON.stringify({ event: 'reservation_no_trade_id', bot_id, signal_id }))
      return { ack: false }
    }

    tradeId = reservedTradeId
  } else {
    // SELL (EP3): idempotent pending INSERT. Exits are EXEMPT from the per-order/daily BUY notional
    // caps (an exit must always be allowed to reduce exposure), so there is NO atomic cap re-check —
    // the only concurrency concern is a duplicate/retried exit, handled fail-safe by the
    // UNIQUE(bot_id, signal_id) constraint (23505 → dedup ack). The pending row still exists BEFORE
    // createOrder (crash-recovery invariant); requested_notional_usdt is NULL so this row never counts
    // toward, nor consumes, the BUY daily cap.
    const { data: sellIns, error: sellErr } = await supabase
      .from('trades')
      .insert({
        bot_id,
        user_id:                 bot.user_id,
        signal_id,
        client_order_id:         clientOrderId,
        side,
        trading_pair:            bot.trading_pair,
        quantity,
        requested_notional_usdt: null,
        status:                  'pending',
      })
      .select('id')
      .single()

    if (sellErr) {
      if ((sellErr as { code?: string }).code === '23505') {
        // Duplicate (bot_id, signal_id) — a concurrent/retried exit already reserved. Dedup: ack, no order.
        console.error(JSON.stringify({ event: 'duplicate_signal_race', bot_id, signal_id, side, error: '23505' }))
        return { ack: true }
      }
      // Infra fault — no row inserted. Transient: retry via the visibility timeout. NO order.
      console.error(JSON.stringify({ event: 'sell_reservation_error', bot_id, signal_id, error: (sellErr as { code?: string }).code ?? 'insert_error' }))
      return { ack: false }
    }

    tradeId = (sellIns as { id: string }).id
  }

  console.log(JSON.stringify({
    event:        'trade_pending',
    bot_id,
    trade_id:     tradeId,
    signal_id,
    side,
    quantity,
    trading_pair: bot.trading_pair,
  }))

  const createdAudited = await insertAuditLog(supabase, 'trade', tradeId, 'trade.created',
    {},
    { status: 'pending', bot_id, signal_id, side, trading_pair: bot.trading_pair, quantity },
  )

  // 4A HB-A (pre-order gate): in live tier with fail-closed enabled, NEVER place a real order without a
  // durable trade.created audit. If the audit could not be written, abort BEFORE createOrder. This is a
  // PRE-ORDER SAFETY BLOCK — no order was ever sent to the exchange — so it must NOT be recorded as a
  // normal exchange/order failure ('failed'). trade_status has no 'blocked' value (adding one needs a
  // migration), so use a schema-valid TERMINAL status with an unmistakable block reason + event:
  //   - status 'cancelled' = not executed (like 'failed', excluded from the daily-cap sum), terminal so
  //     a retry dedups cleanly via Step 3 — no 'pending' left behind, no reconciliation ambiguity;
  //   - error_reason 'audit_blocked_before_order' + event 'order_blocked_audit_unavailable' make the
  //     pre-order block unmistakable (never read as an exchange failure).
  if (auditFailClosed && !createdAudited) {
    const { error: blockErr } = await supabase
      .from('trades')
      .update({ status: 'cancelled', error_reason: 'audit_blocked_before_order' })
      .eq('id', tradeId)
    if (blockErr) {
      console.error(JSON.stringify({ event: 'trade_block_mark_error', bot_id, trade_id: tradeId, signal_id, error: blockErr.code }))
    }
    console.error(JSON.stringify({ event: 'order_blocked_audit_unavailable', bot_id, trade_id: tradeId, signal_id, stage: 'trade.created' }))
    return { ack: true }
  }

  // ── Step 8: Execute order ────────────────────────────────────────────────────
  timing.beforeOrder = now()   // EP7: right before the order round-trip
  try {
    const order = await adapter.createOrder({
      symbol:        bot.trading_pair,
      side,
      type:          'market',
      quantity,
      clientOrderId,
    })
    timing.afterOrder = now()  // EP7: order round-trip complete

    // ── Step 9: Update trade status ──────────────────────────────────────────
    const { error: updateError } = await supabase
      .from('trades')
      .update({
        status:                 order.status,
        exchange_order_id:      order.id,
        price_at_execution:     order.price,
        executed_notional_usdt: order.cost ?? null, // final fill notional (USDT) when ccxt reports cost
        filled_at:              order.status === 'filled' ? new Date().toISOString() : null,
      })
      .eq('id', tradeId)

    if (updateError) {
      // createOrder succeeded — order exists on exchange.
      // DB update failed — mark unknown and create reconciliation_job immediately.
      // Ack the message: retrying risks a duplicate order.
      const { error: unknownMarkError } = await supabase
        .from('trades')
        .update({ status: 'unknown', error_reason: 'trade_status_update_failed' })
        .eq('id', tradeId)
      if (unknownMarkError) {
        // Both updates failed — trade stays 'pending'; boot reconciliation is
        // the backstop (>60s). Log loudly so the silent window is observable. (F-04)
        console.error(JSON.stringify({
          event:    'trade_unknown_mark_error',
          bot_id,
          trade_id: tradeId,
          error:    unknownMarkError.code,
        }))
      }

      console.error(JSON.stringify({
        event:             'trade_status_update_error',
        bot_id,
        trade_id:          tradeId,
        exchange_order_id: order.id,
        error:             updateError.code,
      }))
      await insertAuditLog(supabase, 'trade', tradeId, 'trade.unknown',
        { status: 'pending' },
        { status: 'unknown', error_reason: 'trade_status_update_failed' },
      )

      // Create reconciliation_job immediately — don't wait for boot (ENG-004)
      const { error: reconError } = await supabase
        .from('reconciliation_jobs')
        .upsert({ trade_id: tradeId }, { onConflict: 'trade_id', ignoreDuplicates: true })
      if (reconError) {
        console.error(JSON.stringify({
          event:    'reconciliation_job_create_error',
          trade_id: tradeId,
          bot_id,
          error:    reconError.code,
        }))
      }

      return { ack: true } // order is on exchange — don't retry, reconciliation handles it
    }

    // Step 9 success: audit then conditionally reset circuit breaker
    const filledAudited = await insertAuditLog(supabase, 'trade', tradeId, `trade.${order.status}`,
      { status: 'pending' },
      { status: order.status, exchange_order_id: order.id },
    )
    // 4A HB-B (post-order): the order is already placed — it CANNOT be un-placed, so we never revert the
    // known-good trade. But in live tier we must never SILENTLY drop the fill audit: alert loudly so the
    // missing trail is observable. The `trades` row remains the state-of-record.
    if (auditFailClosed && !filledAudited) {
      console.error(JSON.stringify({ event: 'audit_write_failed_post_order', bot_id, trade_id: tradeId, signal_id, status: order.status }))
    }

    // H-3: a success-path 'unknown' status (createOrder returned a status ccxt maps to 'unknown')
    // leaves a possibly-live order with no reconciliation handoff — unlike Case C and the
    // status-update-failure path, both of which create a reconciliation_job. Step 3.5 already blocks
    // the bot on 'unknown', but without a job the trade is only resolved on the next boot. Mirror
    // Case C so a (runtime or boot) resolver picks it up promptly. No behavior change for
    // filled/submitted/cancelled.
    if (order.status === 'unknown') {
      const { error: reconError } = await supabase
        .from('reconciliation_jobs')
        .upsert({ trade_id: tradeId }, { onConflict: 'trade_id', ignoreDuplicates: true })
      if (reconError) {
        console.error(JSON.stringify({
          event:    'reconciliation_job_create_error',
          trade_id: tradeId,
          bot_id,
          signal_id,
          error:    reconError.code,
        }))
      }
      console.error(JSON.stringify({
        event:    'trade_unknown_reconciliation_created',
        bot_id,
        trade_id: tradeId,
        signal_id,
        error:    'createOrder_returned_unknown_status',
      }))
    }

    // Reset circuit breaker only on filled or submitted — NOT cancelled (ENG-008).
    // Cancelled market orders are anomalies, not successes; resetting would mask failures.
    if (bot.consecutive_failures > 0 &&
        (order.status === 'filled' || order.status === 'submitted')) {
      await supabase
        .from('bots')
        .update({ consecutive_failures: 0 })
        .eq('id', bot_id)
    }

    console.log(JSON.stringify({
      event:             'trade_executed',
      bot_id,
      trade_id:          tradeId,
      exchange_order_id: order.id,
      status:            order.status,
    }))

    // EP7: per-stage latency (ms). setup = bot/credential/gates/adapter; pre_order = market rules +
    // balance/price + reservation (exchange reads + one DB round-trip); order = the createOrder
    // round-trip (the critical placement latency); total = worker wall-clock for this message. Carries
    // the venue so latencies can be compared per exchange. Logging-only — never affects execution.
    console.log(JSON.stringify({
      event:     'trade_timing',
      bot_id,
      trade_id:  tradeId,
      exchange:  exchangeId,
      side,
      ms: {
        setup:     timing.adapterReady - timing.start,
        pre_order: timing.beforeOrder  - timing.adapterReady,
        order:     timing.afterOrder   - timing.beforeOrder,
        total:     timing.afterOrder   - timing.start,
      },
    }))

    return { ack: true }

  } catch (e) {
    // ── Step 10: Error handling — three-way split ──────────────────────────────
    const errorName = e instanceof Error ? e.constructor.name : 'unknown'

    // ── Branch 1: Immediate disable (ENG-002, ENG-003) ────────────────────────
    // VaultSecretNotFoundError: secret deleted — credential is gone permanently.
    // ExchangeAuthError: API key invalid/revoked — permanent until rotated.
    // No threshold — disable bot + credential immediately, no failures++.
    // ── Branch 0: -2015 ambiguous (mainnet IP/permission) ─────────────────────
    // A good, IP-allowlisted key from a not-yet-allowlisted egress IP returns the SAME -2015 as a bad key,
    // so we must NOT invalidate the credential. The auth failed → the order was almost certainly NOT placed;
    // mark the trade failed + DLQ (for the audit trail), then PAUSE (disarm) the bot WITHOUT touching
    // credential.status, and surface an operator-actionable reason. Fail-closed; no retry loop.
    if (e instanceof ExchangeAuthIpError) {
      await supabase.from('trades').update({ status: 'failed', error_reason: errorName }).eq('id', tradeId)
      await insertAuditLog(supabase, 'trade', tradeId, 'trade.failed',
        { status: 'pending' },
        { status: 'failed', error_reason: errorName },
      )
      const { error: dlqErrorIp } = await supabase.from('trades_dlq').insert({
        trade_id:       tradeId,
        bot_id,
        signal_id,
        raw_payload:    { side, quantity, trading_pair: bot.trading_pair },
        failure_reason: errorName,
        retry_count:    0,
      })
      if (dlqErrorIp) {
        console.error(JSON.stringify({ event: 'dlq_insert_error', trade_id: tradeId, bot_id, error: dlqErrorIp.code }))
      }
      await pauseBotForAuthAttention(supabase, bot, signal_id, 'ip_or_permission')
      console.error(JSON.stringify({ event: 'trade_failed_auth_ip', bot_id, trade_id: tradeId, signal_id }))
      return { ack: true }
    }

    if (e instanceof VaultSecretNotFoundError || e instanceof ExchangeAuthError) {
      await supabase.from('trades').update({ status: 'failed', error_reason: errorName }).eq('id', tradeId)
      await insertAuditLog(supabase, 'trade', tradeId, 'trade.failed',
        { status: 'pending' },
        { status: 'failed', error_reason: errorName },
      )

      const { error: dlqError } = await supabase.from('trades_dlq').insert({
        trade_id:       tradeId,
        bot_id,
        signal_id,
        raw_payload:    { side, quantity, trading_pair: bot.trading_pair },
        failure_reason: errorName,
        retry_count:    0,
      })
      if (dlqError) {
        console.error(JSON.stringify({ event: 'dlq_insert_error', trade_id: tradeId, bot_id, error: dlqError.code }))
      }

      await disableCredentialAndBot(supabase, bot, signal_id, errorName)
      console.error(JSON.stringify({
        event:    'trade_failed_credential_invalid',
        bot_id,
        trade_id: tradeId,
        signal_id,
        error:    errorName,
      }))
      return { ack: true }

    // ── Branch 2: Threshold-based permanent (ENG-005) ─────────────────────────
    // Exchange explicitly rejected the order — retrying the same signal won't help.
    // Increments consecutive_failures; circuit breaker trips at MAX_CONSECUTIVE_FAILURES.
    } else if (e instanceof ExchangeRejectedError) {
      await supabase.from('trades').update({ status: 'failed', error_reason: errorName }).eq('id', tradeId)
      await insertAuditLog(supabase, 'trade', tradeId, 'trade.failed',
        { status: 'pending' },
        { status: 'failed', error_reason: errorName },
      )

      const newFailures                        = bot.consecutive_failures + 1
      const botUpdate: Record<string, unknown> = { consecutive_failures: newFailures }
      if (newFailures >= MAX_CONSECUTIVE_FAILURES) {
        botUpdate.status = 'error'
        console.error(JSON.stringify({ event: 'bot_circuit_breaker_tripped', bot_id, consecutive_failures: newFailures }))
      }
      await supabase.from('bots').update(botUpdate).eq('id', bot_id)
      if (newFailures >= MAX_CONSECUTIVE_FAILURES) {
        await insertAuditLog(supabase, 'bot', bot_id, 'bot.circuit_breaker',
          { status: bot.status, consecutive_failures: bot.consecutive_failures },
          { status: 'error',    consecutive_failures: newFailures },
        )
      }

      const { error: dlqError } = await supabase.from('trades_dlq').insert({
        trade_id:       tradeId,
        bot_id,
        signal_id,
        raw_payload:    { side, quantity, trading_pair: bot.trading_pair },
        failure_reason: errorName,
        retry_count:    0,
      })
      if (dlqError) {
        console.error(JSON.stringify({ event: 'dlq_insert_error', trade_id: tradeId, bot_id, error: dlqError.code }))
      }

      console.error(JSON.stringify({
        event:    'trade_failed_permanent',
        bot_id,
        trade_id: tradeId,
        signal_id,
        error:    errorName,
      }))
      return { ack: true }

    // ── Branch 3: Transient — inline fetchOrder (ENG-004, Option B) ───────────
    // createOrder timed out or exchange was unreachable.
    // We don't know if the order reached the exchange — call fetchOrder once to resolve.
    } else {
      let fetchedOrder: Awaited<ReturnType<typeof adapter.fetchOrder>> | 'fetch_failed' = 'fetch_failed'
      try {
        fetchedOrder = await adapter.fetchOrder({
          clientOrderId,
          symbol: bot.trading_pair,
        })
      } catch {
        // fetchOrder also failed transiently — exchange genuinely unreachable
        fetchedOrder = 'fetch_failed'
      }

      if (fetchedOrder !== 'fetch_failed' && fetchedOrder !== null) {
        // ── Case A: Order found on exchange — resolved inline ─────────────────
        const resolvedStatus = fetchedOrder.status
        await supabase.from('trades').update({
          status:                 resolvedStatus,
          exchange_order_id:      fetchedOrder.id,
          price_at_execution:     fetchedOrder.price,
          executed_notional_usdt: fetchedOrder.cost ?? null, // M-6: persist executed notional (P&L basis)
          filled_at:              resolvedStatus === 'filled' ? new Date().toISOString() : null,
        }).eq('id', tradeId)

        await insertAuditLog(supabase, 'trade', tradeId, `trade.${resolvedStatus}`,
          { status: 'pending' },
          { status: resolvedStatus, exchange_order_id: fetchedOrder.id, resolved_via: 'inline_fetch' },
        )

        // Reset circuit breaker on filled/submitted only — NOT cancelled (ENG-008)
        if (bot.consecutive_failures > 0 &&
            (resolvedStatus === 'filled' || resolvedStatus === 'submitted')) {
          await supabase.from('bots').update({ consecutive_failures: 0 }).eq('id', bot_id)
        }

        console.log(JSON.stringify({
          event:             'trade_resolved_inline_fetch',
          bot_id,
          trade_id:          tradeId,
          signal_id,
          status:            resolvedStatus,
          exchange_order_id: fetchedOrder.id,
          original_error:    errorName,
        }))
        return { ack: true }

      } else if (fetchedOrder === null) {
        // ── Case B (H-5): OrderNotFound after a submit timeout is UNCERTAIN, not proof of non-placement ──
        // A createOrder that reached Binance and was accepted can still time out on the response; the
        // follow-up fetchOrder can then briefly return OrderNotFound due to propagation lag. Writing a
        // terminal 'failed' here would silently drop a real, live position. So we DO NOT finalize: mark
        // 'unknown' + open a reconciliation_job (mirrors Case C). The read-only resolver re-checks the
        // order with fresh propagation time; if it is still OrderNotFound there it resolves to terminal
        // 'failed', so a genuinely-never-placed order is never wedged forever. Step 3.5 blocks the bot
        // meanwhile so no second order can race the ambiguous one.
        await supabase.from('trades').update({
          status:       'unknown',
          error_reason: 'order_not_found_after_timeout',
        }).eq('id', tradeId)

        await insertAuditLog(supabase, 'trade', tradeId, 'trade.unknown',
          { status: 'pending' },
          { status: 'unknown', error_reason: 'order_not_found_after_timeout', resolved_via: 'inline_fetch' },
        )

        const { error: reconError } = await supabase
          .from('reconciliation_jobs')
          .upsert({ trade_id: tradeId }, { onConflict: 'trade_id', ignoreDuplicates: true })
        if (reconError) {
          console.error(JSON.stringify({
            event:    'reconciliation_job_create_error',
            trade_id: tradeId,
            bot_id,
            signal_id,
            error:    reconError.code,
          }))
        }

        console.error(JSON.stringify({
          event:          'trade_uncertain_order_not_found',
          bot_id,
          trade_id:       tradeId,
          signal_id,
          original_error: errorName,
          // S4A: original ccxt cause class (+ httpStatus) — non-secret; was previously
          // swallowed when createOrder wrapped unknown errors as ExchangeUnavailableError().
          original_error_detail: e instanceof ExchangeUnavailableError ? e.detail : undefined,
        }))
        return { ack: true }

      } else {
        // ── Case C: fetchOrder also failed — genuinely unknown state ──────────
        // Both createOrder and fetchOrder are unavailable (network outage).
        // Mark unknown, create reconciliation_job, block bot via Step 3.5.
        await supabase.from('trades').update({ status: 'unknown', error_reason: errorName }).eq('id', tradeId)
        await insertAuditLog(supabase, 'trade', tradeId, 'trade.unknown',
          { status: 'pending' },
          { status: 'unknown', error_reason: errorName },
        )

        const { error: reconError } = await supabase
          .from('reconciliation_jobs')
          .upsert({ trade_id: tradeId }, { onConflict: 'trade_id', ignoreDuplicates: true })
        if (reconError) {
          console.error(JSON.stringify({
            event:    'reconciliation_job_create_error',
            trade_id: tradeId,
            bot_id,
            signal_id,
            error:    reconError.code,
          }))
        }

        console.error(JSON.stringify({
          event:    'trade_unknown_reconciliation_created',
          bot_id,
          trade_id: tradeId,
          signal_id,
          error:    errorName,
          code:     e instanceof VaultUnavailableError ? e.code : undefined, // F-14
        }))
        return { ack: true }
      }
    }
  }
}

// ─── Queue preflight ──────────────────────────────────────────────────────────

/**
 * Verifies the pgmq_read RPC exists and is callable BEFORE entering the poll
 * loop. Only runs when QUEUE_ENABLED=true.
 *
 * Rationale: if the RPC is missing (PGRST202), the poll loop would log
 * queue_read_error on every interval forever — an unhealthy, alert-worthy
 * container masquerading as "running". Instead we fail fast with a single
 * startup_error and exit(1); Railway's restart policy then retries a bounded
 * number of times before giving up, surfacing the problem instead of hiding it.
 *
 * Non-destructive probe: qty:0 reads zero messages, so it cannot consume, hide
 * (via visibility timeout), or otherwise mutate a real queued signal. We only
 * care whether the RPC resolves without a "function does not exist" error.
 *
 * TODO(Sprint 3): confirm pgmq_read accepts qty:0 when the wrapper migration
 *   lands. This path never executes until QUEUE_ENABLED=true, which is only set
 *   after that wrapper exists — so there is no Sprint 2 runtime risk.
 */
async function preflightQueue(supabase: SupabaseClient): Promise<void> {
  const { error } = await supabase.rpc('pgmq_read', {
    queue_name: QUEUE_NAME,
    vt:         0,
    qty:        0,
  })

  if (error) {
    console.error(JSON.stringify({
      event:  'startup_error',
      reason: 'queue_rpc_unavailable',
      rpc:    'pgmq_read',
      error:  error.code,
    }))
    process.exit(1)
  }

  console.log(JSON.stringify({ event: 'queue_preflight_ok' }))
}

// ─── Poll once ────────────────────────────────────────────────────────────────

/**
 * Reads one message from pgmq, processes it, and acks if appropriate.
 *
 * Only reached when QUEUE_ENABLED=true AND preflightQueue() has already proven
 * pgmq_read exists — so a PGRST202 here would be a genuine regression, not the
 * expected "RPC not built yet" state.
 *
 * pgmq_read / pgmq_delete are public-schema wrappers created in a future
 * migration (Sprint 3).
 */
async function pollOnce(supabase: SupabaseClient): Promise<void> {
  const { data: messages, error: readError } = await supabase
    .rpc('pgmq_read', {
      queue_name: QUEUE_NAME,
      vt:         VISIBILITY_TIMEOUT_S,
      qty:        1,
    })

  if (readError) {
    console.error(JSON.stringify({
      event: 'queue_read_error',
      error: readError.code,
    }))
    return
  }

  if (!messages || (messages as PgmqMessage[]).length === 0) return

  const msg = (messages as PgmqMessage[])[0]

  console.log(JSON.stringify({
    event:   'message_received',
    msg_id:  msg.msg_id,
    bot_id:  msg.message?.bot_id,
    side:    msg.message?.side,
    read_ct: msg.read_ct,   // WB7: pgmq redelivery counter (1 = first delivery)
  }))

  // WB7 instrumentation — measure processMessage wall-time on a monotonic clock
  // (process.hrtime, immune to wall-clock adjustments) and surface pgmq's
  // redelivery counter. processing_duration_ms is the empirical input to the
  // visibility_timeout worst_case formula; read_ct is the zero-duplicate-redelivery
  // evidence channel (must stay 1 while VISIBILITY_TIMEOUT_S > worst_case).
  // Pure measurement: no branch, ack, or DB behaviour depends on these values.
  const startNs = process.hrtime.bigint()
  const { ack } = await processMessage(supabase, msg)
  const processingDurationMs = Math.round(Number(process.hrtime.bigint() - startNs) / 1e6)

  console.log(JSON.stringify({
    event:                  'message_processed',
    msg_id:                 msg.msg_id,
    ack,
    read_ct:                msg.read_ct,
    processing_duration_ms: processingDurationMs,
  }))

  if (ack) {
    const { error: ackError } = await supabase
      .rpc('pgmq_delete', {
        queue_name: QUEUE_NAME,
        msg_id:     msg.msg_id,
      })

    if (ackError) {
      // Non-fatal: message re-appears after visibility timeout expires.
      // Idempotency check in processMessage prevents re-execution.
      console.error(JSON.stringify({
        event:  'queue_ack_error',
        msg_id: msg.msg_id,
        error:  ackError.code,
      }))
    } else {
      console.log(JSON.stringify({ event: 'message_acked', msg_id: msg.msg_id }))
    }
  } else {
    // Not acking: visibility timeout will re-expose for retry.
    console.log(JSON.stringify({
      event:  'message_not_acked',
      msg_id: msg.msg_id,
      reason: 'transient_failure',
    }))
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

/**
 * Boot reconciliation + lifecycle, branching on queueEnabled. Separated from
 * main() (which owns env validation + client creation) so it can be unit-tested
 * with an injected Supabase mock.
 *
 *   queueEnabled=false (Sprint 2 Railway deploy):
 *     reconcile → log worker_queue_disabled once → keep process alive until
 *     SIGTERM/SIGINT → exit cleanly. Never enters the poll loop, so it cannot
 *     spam queue_read_error against a not-yet-built pgmq_read RPC. Boot
 *     reconciliation still runs — it is the canary that proves the service_role
 *     GRANTs (migration 006) cleared the 42501 error.
 *
 *   queueEnabled=true (Sprint 3+):
 *     reconcile → preflightQueue (fail fast if pgmq_read missing) → poll loop.
 */
async function runWorker(supabase: SupabaseClient, queueEnabled: boolean): Promise<void> {
  const bootStuckCount = await runBootReconciliation(supabase)

  // S4-3a: resolve the reconciliation_jobs just created — fetchOrder (READ-ONLY) → terminal status.
  // Boot-time resolve; the runtime periodic scan (S4-3b) now runs below via startReconciliationScan
  // (flag-gated, default OFF). Both reuse this same read-only resolver — NEVER places an order.
  // Never throws into boot: a failure here must not block startup or the (disabled) keep-alive.
  try {
    await resolvePendingReconciliations(supabase, {
      isProduction: process.env.PRAXIS_IS_PRODUCTION === 'true',
      exchangeHttpsProxy: process.env.EXCHANGE_HTTPS_PROXY?.trim() || null,   // A1 Option B (proxy mode)
      nativeEgressAllowed: process.env.EXCHANGE_EGRESS_MODE === 'native',      // A1 Option A (B0 native mode)
    })
  } catch (e) {
    console.error(JSON.stringify({
      event: 'reconciliation_resolve_fatal',
      error: e instanceof Error ? e.constructor.name : 'unknown',
    }))
  }

  // Graceful shutdown — Railway sends SIGTERM before container termination.
  // Node.js is single-threaded: SIGTERM sets running=false during the next await.
  // The current pollOnce() call (including any message processing) completes first.
  // Registered for BOTH paths: the disabled keep-alive also unblocks on signal.
  let running = true
  let wake: () => void = () => {}
  const keepAlive = new Promise<void>(resolve => { wake = resolve })
  const stop = (reason: string): void => {
    console.log(JSON.stringify({ event: 'worker_stopping', reason }))
    running = false
    wake()
  }
  process.once('SIGTERM', () => stop('SIGTERM'))
  process.once('SIGINT', () => stop('SIGINT'))

  // Operator-console runtime status (Slice 1a): publish worker-observed state to public.worker_status
  // on boot + every 60s, and one best-effort 'stopping' row on shutdown. Non-fatal, unref'd,
  // WRITE-ONLY — cannot affect trading. Dormant until migration 015 is applied + this build is
  // deployed; a missing table logs ONE throttled non-fatal error (then a recovery log once applied) —
  // never 60s noise, never worker-health failure.
  const workerStatusWriter = startWorkerStatus({
    supabase,
    fields: {
      queueEnabled,
      isProduction:   process.env.PRAXIS_IS_PRODUCTION === 'true',
      bootStuckCount,
      workerState:    queueEnabled ? 'running' : 'disabled',
    },
  })

  // Slice 4C — webhook requeue recovery sweeper. Runs on BOTH the enabled and disabled paths (a
  // queue_failed / stale-accepted row must recover even when the poll loop is off). Flag-gated, default
  // OFF (dark launch): unset ⇒ no-op, no timer. Out-of-band from trading — no exchange call, no secret.
  const webhookRequeueSweeper = startWebhookRequeueSweeper({
    supabase,
    enabled: process.env.WEBHOOK_REQUEUE_SWEEPER_ENABLED === 'true',
  })

  // S4-3b — runtime periodic reconciliation scan. Runs on BOTH paths (a stuck pending/unknown
  // trade must resolve even when the poll loop is off). Flag-gated, default OFF (dark launch):
  // unset ⇒ no timer, no work. Delegates to the SAME read-only resolver as the boot scan — no
  // exchange order, egress fail-closed + credential-ownership inherited from defaultAdapterFor.
  const reconciliationScan = startReconciliationScan({
    supabase,
    enabled: process.env.RECONCILIATION_SCAN_ENABLED === 'true',
    isProduction: process.env.PRAXIS_IS_PRODUCTION === 'true',
    exchangeHttpsProxy: process.env.EXCHANGE_HTTPS_PROXY?.trim() || null,   // A1 Option B (proxy mode)
    nativeEgressAllowed: process.env.EXCHANGE_EGRESS_MODE === 'native',      // A1 Option A (B0 native mode)
    visibilityTimeoutS: VISIBILITY_TIMEOUT_S, // clamp staleness threshold ≥ visibility + margin
  })

  // M8-validate — read-only credential validation. Drains the DEDICATED `credential_validations`
  // queue (isolated from trade_signals) and proves a connected key authenticates via fetchBalance —
  // NEVER an order. Runs on BOTH paths (an operator must be able to validate a key even when the
  // trade poll loop is off). Flag-gated, default OFF (dark launch): unset ⇒ no timer, no work.
  // Egress + env + venue + ownership rails are inherited from the trade path (fail-closed).
  const credentialValidation = startCredentialValidation({
    supabase,
    enabled:      process.env.CREDENTIAL_VALIDATION_ENABLED === 'true',
    isProduction: process.env.PRAXIS_IS_PRODUCTION === 'true',
  })

  // 045 — expire stale pending proposals (per-order approval). Flag-gated, default OFF (dark launch until the
  // approval feature ships). Marks un-approved proposals past their expires_at as 'expired'; no order ever placed.
  const proposalSweeper = startProposalSweeper({
    supabase,
    enabled: process.env.PROPOSAL_SWEEPER_ENABLED === 'true',
  })

  if (!queueEnabled) {
    // Disabled path: idle, healthy, silent. One log line, then keep-alive.
    console.log(JSON.stringify({ event: 'worker_queue_disabled' }))
    // A pending Promise does NOT keep the Node event loop alive on its own, and
    // neither does a signal listener — without a ref'd handle the process exits 0
    // and Railway shows the container as "Completed" instead of a running,
    // always-on worker. A no-op interval is a ref'd handle that keeps the loop
    // alive; cleared on shutdown so SIGTERM/SIGINT still exit cleanly.
    const heartbeat = setInterval(() => {}, 60_000)
    await keepAlive
    clearInterval(heartbeat)
    webhookRequeueSweeper.stop()
    reconciliationScan.stop()
    credentialValidation.stop()
    proposalSweeper.stop()
    await workerStatusWriter.stop()
    console.log(JSON.stringify({ event: 'worker_stopped' }))
    return
  }

  // Enabled path: prove the queue RPC exists before committing to the loop.
  await preflightQueue(supabase)

  console.log(JSON.stringify({ event: 'worker_running' }))

  while (running) {
    try {
      await pollOnce(supabase)
    } catch (e) {
      // Unexpected error in poll loop — log and continue, never crash the Worker
      console.error(JSON.stringify({
        event: 'poll_loop_error',
        error: e instanceof Error ? e.constructor.name : 'unknown',
      }))
    }

    if (running) {
      await new Promise<void>(resolve => setTimeout(resolve, POLL_INTERVAL_MS))
    }
  }

  webhookRequeueSweeper.stop()
  reconciliationScan.stop()
  credentialValidation.stop()
  await workerStatusWriter.stop()
  console.log(JSON.stringify({ event: 'worker_stopped' }))
}

async function main(): Promise<void> {
  const { supabaseUrl, serviceRoleKey, isProduction, queueEnabled } = validateEnv()

  // auth.persistSession = false: Worker is a server process, not a browser client.
  // Every call authenticates via the service_role JWT — no session needed.
  const supabase = createClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false },
  })

  console.log(JSON.stringify({
    event:                'worker_starting',
    queue:                QUEUE_NAME,
    queue_enabled:        queueEnabled,
    visibility_timeout_s: VISIBILITY_TIMEOUT_S,
    poll_interval_ms:     POLL_INTERVAL_MS,
    is_production:        isProduction,
    doppler_environment:  process.env.DOPPLER_ENVIRONMENT ?? 'unknown',
  }))

  // S4-1 dead-man heartbeat — out-of-band, default OFF (no HEALTHCHECKS_URL → no-op). Started here
  // in main() ONLY, never in runWorker/pollOnce/processMessage; stopped on shutdown. Fire-and-forget,
  // unref'd timer, failures swallowed — cannot block, delay, or affect trading.
  configureAlerts({ url: process.env.ALERT_WEBHOOK_URL }) // Plan v1.1 · 1.5 — default OFF; POSTs operator alerts when set
  const heartbeat = startHeartbeat({ url: process.env.HEALTHCHECKS_URL })
  try {
    await runWorker(supabase, queueEnabled)
  } finally {
    heartbeat?.stop()
  }
}

// ─── Entry guard ──────────────────────────────────────────────────────────────
// require.main === module is false when imported by ts-jest.
// Prevents main() from executing during unit tests.

if (require.main === module) {
  main().catch(e => {
    console.error(JSON.stringify({
      event: 'worker_fatal',
      error: e instanceof Error ? e.constructor.name : 'unknown',
    }))
    process.exit(1)
  })
}

// ─── Test exports ─────────────────────────────────────────────────────────────
// Exported for unit testing only.

export { runBootReconciliation, processMessage, validateEnv, preflightQueue, pollOnce, runWorker }
export type { PgmqMessage, TradeSignalMessage }
