// AUTO-GENERATED by scripts/sample-logo-palettes.mjs — do not edit by hand.
// Pixel-exact per-skin letter colours sampled from public/logo-{skin}.png (the real logo
// art), used by CarvedTitle so each screen's carved title matches TODAY's logo per skin.
export type SkinKey = "navy" | "peach" | "amber" | "aurora";
export const LOGO_PALETTES: Record<SkinKey, string[]> = {
  "navy": [
    "#8cb3db",
    "#699edb",
    "#4887da",
    "#5791de",
    "#4482dc",
    "#3d79d8",
    "#1f5fc8",
    "#aed2fa",
    "#b2d5fa",
    "#8abaf2",
    "#5b99ea",
    "#3e80e0",
    "#548fe3",
    "#2e70d6"
  ],
  "peach": [
    "#e0a07d",
    "#e78b6c",
    "#ed7559",
    "#f07f66",
    "#f4755a",
    "#f0665b",
    "#e84c68",
    "#ffc2a0",
    "#ffc4a4",
    "#ffab8f",
    "#ff8a6e",
    "#fb7458",
    "#fb8269",
    "#f05b50"
  ],
  "amber": [
    "#e0a737",
    "#e69314",
    "#ec8010",
    "#f08b24",
    "#f47f2a",
    "#f06e2f",
    "#e24d1a",
    "#ffc85c",
    "#ffca63",
    "#ffb33f",
    "#ff9528",
    "#fb7e24",
    "#fb8c3e",
    "#f0631f"
  ],
  "aurora": [
    "#73b7ab",
    "#4aa99d",
    "#5db1a7",
    "#2e9083",
    "#339387",
    "#358d81",
    "#2c6e62",
    "#8fd1c5",
    "#95d3c8",
    "#69bfb5",
    "#3fa395",
    "#36978b",
    "#55a69c",
    "#358e81"
  ]
};
